### PR TITLE
Bringing capstone aarch64 up to a nearly normalized state.

### PR DESCRIPTION
**Pull request by nathanhjay**
There don't seem to be any more normalization steps for Capstone aarch64, but exhaustive testing has not been performed. From here, any normalization steps could occur with other decoders on a general aarch64 normalization branch.

### CODE REVIEW

**Comment by jdetter** [comment]
How many issues do you get between capstone and xed with no normalization for like 100,000 random instructions?

**Comment by nathanhjay** [comment]
That's on the x86 side. This branch was strictly aarch64. On aarch64, comparing to LLVM with no normalization, I get 2,585 unique reports (and 222075 duplicates) out of 1,000,000 instructions. With normalization in the current state (only minor work to do on the LLVM side), I'm down to 74 unique issues of out 1,000,000 instructions (with 4680 duplicates).

I did a quick x86 comparison to humor you. Between xed and capstone with no normalization, I get 11,762 unique reports and 384,600 duplicates from 1,000,000 instructions. So roughly 60% match without any normalization.

**Comment by jdetter** [comment]
74 reports out of 1,000,000 instructions is really really good!

**Comment by nathanhjay** [comment]
I did a bit longer of a run before committing. Out of 100,000,000 instructions, I got 104 differences between normalized LLVM and Capstone broken down like this:
80 unsupported instructions on LLVM
12 normalization issues on the LLVM side involving complex instruction aliases (opcode and operands both change).
8 known LLVM errors (all replicas of a BFC issue)
3 system register issues not in the manual
1 unknown, possible misprint?

I'll open a generic aarch64 normalization branch and fix the 12 reports that need changes to LLVM. I'll have to update GNU normalization to handle those cases as well.

**Pull request merged**
